#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 21 15:30:16 2019

@author: thuan ngo tungfint
"""

from flask import Flask, render_template, request
from flask_cors import CORS, cross_origin
from elasticsearch import Elasticsearch
import requests
import json
from querybuilder.rules import Rule
from flask_restful import  Api
from source.model.segmentation import ExecuteSegmentation
from source.model.personalization import ExecutePersonalization
from source.model.DemoPersonalizationTrigger import DemoPersonalizationTrigger
from source.model.DemoSegmentation import DemoSegmentation


import source.utilities.jquerybuilder2elasticquery

es = Elasticsearch( hosts = [{'host': '35.237.224.155', 'port': 9200}])
res = requests.get('http://35.237.224.155:9200')
#print(res)

app = Flask(__name__)
cors = CORS(app, resources={r"/method/*": {"origins": "*"}})
app.config['CORS_HEADERS'] = 'Content-Type'

############################# Webserver Controller ###########################################################
@app.route("/")
def home():
    with open("MasterFile.json") as f:
        data = json.load(f)
    return render_template("index.html",indices = data)


@app.route("/query_elastic", methods=['POST'])
def query_elaticsearch():
    jsonRule = request.get_json();
    index = jsonRule['index'];
    query = jsonRule['query'];
    jqueryRule = Rule(query)
    q = source.utilities.jquerybuilder2elasticquery.to_esl_query(jqueryRule)
    res = es.search(index=index, body={'query':q.to_dict()})
    return json.dumps({'index' : index, 'query': q.to_dict(),'result':str(res['hits']['hits'])});

# ES inf

####################### API Portal Controller ###########################################################

_index_query = 'queries'
_type_query = 'query'

_index_seg = 'segmentations'
_type_seg = 'segmentation'

_index_per = 'personalizations'
_doc_per = 'personalization'

_index_assignment = 'assignments'
_type_assignment = 'assignment'

_index_assignedcontent = 'assigned_contents'
_type_assignedcontent = 'assigned_content'

api = Api(app)

# =============================================================================
# Segmentation
# =============================================================================

ExecuteSegmentation.make_api( es,_index_seg, _index_query)

api.add_resource(ExecuteSegmentation, "/method/segmentation/execute/<string:segID>") #  EXECUTE segmentation

# =============================================================================
# Personalization
# =============================================================================

ExecutePersonalization.make_api( es, _index_per, _index_query)

api.add_resource(ExecutePersonalization, "/method/personalization/execute/<string:userID>/<string:perID>") #  EXECUTE personalization

# =============================================================================
# DemoPersonalizationTrigger
# =============================================================================

DemoPersonalizationTrigger.make_api( es, _index_query, _index_assignment, _index_per, _index_assignedcontent, _type_assignedcontent)

api.add_resource(DemoPersonalizationTrigger, "/method/demoPersonalizationTrigger/<string:userID>/<string:triggerID>")

# =============================================================================
# DemoSegmentation
# =============================================================================

DemoSegmentation.make_api( es, _index_query, _index_seg, _index_per, _index_assignedcontent, _type_assignedcontent)

api.add_resource(DemoSegmentation, "/method/demoSegmentation/<string:segID>/<string:contentID>")


if __name__ == "__main__":
    app.run(debug=True, host='0.0.0.0')
