# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Query(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, query_id: str=None, query_name: str=None, content: str=None):  # noqa: E501
        """Query - a model defined in Swagger

        :param query_id: The query_id of this Query.  # noqa: E501
        :type query_id: str
        :param query_name: The query_name of this Query.  # noqa: E501
        :type query_name: str
        :param content: The content of this Query.  # noqa: E501
        :type content: str
        """
        self.swagger_types = {
            'query_id': str,
            'query_name': str,
            'content': str
        }

        self.attribute_map = {
            'query_id': 'queryID',
            'query_name': 'queryName',
            'content': 'content'
        }

        self._query_id = query_id
        self._query_name = query_name
        self._content = content

    @classmethod
    def from_dict(cls, dikt) -> 'Query':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Query of this Query.  # noqa: E501
        :rtype: Query
        """
        return util.deserialize_model(dikt, cls)

    @property
    def query_id(self) -> str:
        """Gets the query_id of this Query.


        :return: The query_id of this Query.
        :rtype: str
        """
        return self._query_id

    @query_id.setter
    def query_id(self, query_id: str):
        """Sets the query_id of this Query.


        :param query_id: The query_id of this Query.
        :type query_id: str
        """

        self._query_id = query_id

    @property
    def query_name(self) -> str:
        """Gets the query_name of this Query.


        :return: The query_name of this Query.
        :rtype: str
        """
        return self._query_name

    @query_name.setter
    def query_name(self, query_name: str):
        """Sets the query_name of this Query.


        :param query_name: The query_name of this Query.
        :type query_name: str
        """

        self._query_name = query_name

    @property
    def content(self) -> str:
        """Gets the content of this Query.


        :return: The content of this Query.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content: str):
        """Sets the content of this Query.


        :param content: The content of this Query.
        :type content: str
        """

        self._content = content
