# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SegmentationPoint(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, seg_id: str=None, point: int=None):  # noqa: E501
        """SegmentationPoint - a model defined in Swagger

        :param seg_id: The seg_id of this SegmentationPoint.  # noqa: E501
        :type seg_id: str
        :param point: The point of this SegmentationPoint.  # noqa: E501
        :type point: int
        """
        self.swagger_types = {
            'seg_id': str,
            'point': int
        }

        self.attribute_map = {
            'seg_id': 'segID',
            'point': 'point'
        }

        self._seg_id = seg_id
        self._point = point

    @classmethod
    def from_dict(cls, dikt) -> 'SegmentationPoint':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SegmentationPoint of this SegmentationPoint.  # noqa: E501
        :rtype: SegmentationPoint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def seg_id(self) -> str:
        """Gets the seg_id of this SegmentationPoint.


        :return: The seg_id of this SegmentationPoint.
        :rtype: str
        """
        return self._seg_id

    @seg_id.setter
    def seg_id(self, seg_id: str):
        """Sets the seg_id of this SegmentationPoint.


        :param seg_id: The seg_id of this SegmentationPoint.
        :type seg_id: str
        """

        self._seg_id = seg_id

    @property
    def point(self) -> int:
        """Gets the point of this SegmentationPoint.


        :return: The point of this SegmentationPoint.
        :rtype: int
        """
        return self._point

    @point.setter
    def point(self, point: int):
        """Sets the point of this SegmentationPoint.


        :param point: The point of this SegmentationPoint.
        :type point: int
        """

        self._point = point
