# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Segmentation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, seg_id: str=None, seg_name: str=None, query_id: str=None):  # noqa: E501
        """Segmentation - a model defined in Swagger

        :param seg_id: The seg_id of this Segmentation.  # noqa: E501
        :type seg_id: str
        :param seg_name: The seg_name of this Segmentation.  # noqa: E501
        :type seg_name: str
        :param query_id: The query_id of this Segmentation.  # noqa: E501
        :type query_id: str
        """
        self.swagger_types = {
            'seg_id': str,
            'seg_name': str,
            'query_id': str
        }

        self.attribute_map = {
            'seg_id': 'segID',
            'seg_name': 'segName',
            'query_id': 'queryID'
        }

        self._seg_id = seg_id
        self._seg_name = seg_name
        self._query_id = query_id

    @classmethod
    def from_dict(cls, dikt) -> 'Segmentation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Segmentation of this Segmentation.  # noqa: E501
        :rtype: Segmentation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def seg_id(self) -> str:
        """Gets the seg_id of this Segmentation.


        :return: The seg_id of this Segmentation.
        :rtype: str
        """
        return self._seg_id

    @seg_id.setter
    def seg_id(self, seg_id: str):
        """Sets the seg_id of this Segmentation.


        :param seg_id: The seg_id of this Segmentation.
        :type seg_id: str
        """

        self._seg_id = seg_id

    @property
    def seg_name(self) -> str:
        """Gets the seg_name of this Segmentation.


        :return: The seg_name of this Segmentation.
        :rtype: str
        """
        return self._seg_name

    @seg_name.setter
    def seg_name(self, seg_name: str):
        """Sets the seg_name of this Segmentation.


        :param seg_name: The seg_name of this Segmentation.
        :type seg_name: str
        """

        self._seg_name = seg_name

    @property
    def query_id(self) -> str:
        """Gets the query_id of this Segmentation.


        :return: The query_id of this Segmentation.
        :rtype: str
        """
        return self._query_id

    @query_id.setter
    def query_id(self, query_id: str):
        """Sets the query_id of this Segmentation.


        :param query_id: The query_id of this Segmentation.
        :type query_id: str
        """

        self._query_id = query_id
